---
title: "Open Plant Pathology - Member Directory"
output:
  flexdashboard::flex_dashboard:
    theme: flatly
    logo: opp-logo.png
    social: [ "twitter", "facebook" ]
    navbar:
      - { title: "<i class='fa fa-arrow-circle-left' aria-hidden='true'></i> Hompeage", href: "https://www.openplantpathology.org/", align: right }
      - { title: "<i class='fa fa-github' aria-hidden='true'></i> GitHub", href: "https://github.com/openplantpathology/OpenPlantPathology/tree/master/public/directory", align: right }

---

<link rel="stylesheet" href="fontawesome.min.css">

```{r include=FALSE}
# load encrypted API key
GOOGLE_API_KEY <- Sys.getenv("GOOGLE_API_KEY")

# read data from Google Sheets
library(gsheet)

members <-
  gsheet2tbl(
    "https://docs.google.com/spreadsheets/d/1VHGz8oWia5qvleUozznCIgd9bD85XoXm1NWmE6t8nzo/edit?usp=sharing"
  )

# prepare the dataset for table, plot and map
library(tidyverse)
members <- 
  members %>%
  unite(geo,
        location,
        state,
        country,
        remove = F,
        sep = ", ") %>%
  replace_na(list(
    domain1 = "",
    domain2 = "",
    middle_name = "",
    homepage = "",
    twitter = "",
    github = "",
    orcid = ""
  )) %>%
  unite(domain, domain1, domain2, remove = T, sep = ", ") %>%
  unite(name, first_name, middle_name, last_name, sep = " ") %>%
  select(
    name,
    role,
    domain,
    institution,
    location,
    state,
    country,
    homepage,
    twitter,
    github,
    orcid
  )

members$domain <- str_replace_all(members$domain, pattern = ", $", "")

# geocode locations
library(googleway)

set_key("GOOGLE_API_KEY")
# create a vector of locations to geocode
locations <-
  as.list(
    paste(
      members$institution,
      members$location,
      members$state,
      members$country,
      sep = ", "
    )
  )
names(locations) <- members$name

# geocode locations using googleway using all location vars
locations <- lapply(locations, google_geocode, key = GOOGLE_API_KEY)

# unnest the lists and extract only the necessary lat/lng values
# some return more than set of coordinates, take only first row of each
x <- vector("list", length = length(locations))
for (i in 1:length(locations)) {
  x[[i]] <- locations[[i]]$results$geometry$location[1, ]
}
# create a dataframe of lat/lng values
x <- dplyr::bind_rows(x)

# join locations with members list
members <- data.frame(members, x)
```

Column {data-width=700px}
----------------------------------

### <i class="fa fa-table" aria-hidden="true"></i> Member information

```{r echo=FALSE}

# dynamic table using DT package

library(DT)
members_table <- members %>%
  select(name,
         role,
         domain,
         institution,
         country
         # homepage,
         # twitter,
         # github,
         # orcid
  )
# we do not need to show lat and long here

datatable(
  members_table,
  escape = FALSE,
  rownames = FALSE,
  colnames = c(
    "Name",
    "Role",
    "Domain(s)",
    "Institution",
    "Country"
    # "Homepage",
    # "Twitter",
    # "GitHub",
    # "orcid"
  ),
  class = "cell-border stripe",
  options = list(
    order = list(list(0, "asc")),
    # order by first variable
    autoWidth = TRUE,
    columnDefs = list(list(width = "120px", targets = c(0))),
    scroller = TRUE,
    pageLength = 50,
    fontSize = 12,
    lengthMenu = c(50, 100, 200)
  )
) %>%
  formatStyle(
    c(
      "name",
      "role",
      "domain",
      "institution",
      "country"
      # "homepage",
      # "twitter",
      # "github",
      # "orcid"
    ),
    fontSize = "90%")
```


Column {}
----------------------------------

###  <i class="fa fa-map" aria-hidden="true"></i> Global map


```{r echo=FALSE}
library(leaflet)

members <- na.omit(members)

pal <-
  colorFactor(c("#339933", "steelblue"),
              domain = c("Leadership", "Member"))

getColor <- function(members) {
  lapply(members$role, function(role) {
    if (role == "Leadership") {
      "green"
    } else if (role == "Member") {
      "blue"
    }
  })
}
icons <- awesomeIcons(
  icon = "user-o",
  iconColor = "black",
  library = "fa",
  squareMarker = TRUE,
  markerColor = getColor(members)
)

map <- leaflet(members) %>%
  setView(lng = 0, lat = 5, zoom = 1) %>%
  addTiles(urlTemplate = "https://mts1.google.com/vt/lyrs=r&hl=en&src=app&x={x}&y={y}&z={z}&s=G", attribution = "Google") %>%
  addAwesomeMarkers(
    ~lng,
    ~lat,
    icon = icons,
    label = paste(members$name, "- click for details"),
    popup = paste("<b>", members$name, "</b><br>",
                  members$institution, "<br>",
                  members$location, ",", members$country, "<br>",
                  "Domain(s):", members$domain, "<br>"),
    clusterOptions = markerClusterOptions(),
  ) %>%
  addLegend(
    "bottomleft",
    pal = pal,
    values = ~role,
    title = "Role",
    opacity = 1
  ) %>%
  addEasyButton(easyButton(
    icon = "fa-globe",
    title = "Back to initial view",
    onClick = JS("function(btn, map){ map.setZoom(1); }")
  ))
map
```


### <i class="fa fa-bar-chart" aria-hidden="true"></i> Members by knowledge domain


```{r echo=FALSE}
library(plotly)

# sort domains so that we don't have duplicates in different orders
members$domain <- sapply(strsplit(as.character(members$domain), ", "),
                         function(x) paste(x, collapse = " &\n"))

p <- members %>% # we use the original dataframe from Google here
  na.omit() %>%
  ggplot(aes(domain)) +
  geom_bar(aes(fill = domain)) +
  theme(axis.text.x = element_blank(),
        legend.title = element_blank()) +
  labs(y = "Number of Members",
       title = "Members acting in up to two domains")
(gg <- ggplotly(p))
```
